### PR TITLE
Fix issue #50 : scroll-up button that overlaps

### PR DESCRIPTION
**Pull request by zackbmz**
Hello, i just fixed the issue #50  and also tested it and the button doesn"t overlaps anymore ! Thank you for merging this PR !

### CODE REVIEW

**Comment by zackbmz** [comment]
Hello, Can you please test it so you can see that it works ? I would love to have this PR merged before monday ! 

He're is how it's fixed, as you can see there is no longer problem with beetween the scroll up button and the other ones: 
image (6)
image (7)

Thank's a lot @Bjorn-Ironsidee @NuclearReid  @jayabaldwin @Y1va

**Review by NuclearReid — CHANGES_REQUESTED** [review]
nah fam

**Comment by jayabaldwin** [comment]
Thank you for that contribution, however we're only going to submit work done by us as its for a group project. 
Appreciate the input though :)

**Comment by zackbmz** [comment]
lol

**Pull request closed without merging**
